version: '3.8'

services:
  twilio-spam-filter:
    image: php:8.2-apache
    container_name: twilio-spam-filter
    ports:
      - "${PORT:-3010}:80"
    volumes:
      - ./:/var/www/html
    environment:
      # Forwarding destination (Growably webhook URL)
      FORWARDING_URL: ${FORWARDING_URL:-https://services.leadconnectorhq.com/phone-system/voice-call/inbound}
      # Number of spam services that must flag to block (default: 2)
      BLOCK_THRESHOLD: ${BLOCK_THRESHOLD:-2}
      # Apache config
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    command: >
      bash -c "
      composer install --no-interaction --optimize-autoloader &&
      a2enmod rewrite &&
      apache2-foreground
      "
